

export const FETCH_EXPENSE_SUCCESS = 'FETCH_EXPENSE_SUCCESS';
export const FETCH_SINGLE_EXPENSE_SUCCESS = 'FETCH_SINGLE_EXPENSE_SUCCESS';
export const ADD_EXPENSES_SUCCESS = 'ADD_EXPENSES_SUCCESS';
export const UPDATE_EXPENSES_SUCCESS = 'UPDATE_EXPENSES_SUCCESS';
export const DELETE_EXPENSES_SUCCESS = 'DELETE_EXPENSES_SUCCESS';


